from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
import pytest
from sqlalchemy import inspect, text
from sqlalchemy.exc import IntegrityError
from history_data import insert_old_task, snapshot
from migrate import configuration, upgrade
from db import make_engine


@pytest.fixture
def engine(database_url):
    engine = make_engine(database_url)
    try:
        yield engine
    finally:
        outstanding = engine.pool.checkedout()
        engine.dispose()
        assert outstanding == 0


def test_empty_database_upgrades_to_head(database_url, engine):
    upgrade(database_url)
    assert set(inspect(engine).get_table_names()) == {"users", "projects", "project_members", "tasks", "alembic_version"}
    with engine.connect() as connection:
        assert connection.scalar(text("SELECT version_num FROM alembic_version")) == "003_contract"
    command.check(configuration(database_url))


def test_existing_rows_preserved_and_old_writer_still_works(database_url, engine):
    upgrade(database_url, "001_base")
    with engine.begin() as connection:
        user, project, first = insert_old_task(connection)
    upgrade(database_url, "002_expand")
    with engine.begin() as connection:
        insert_old_task(connection, "During expansion", user_id=user, project_id=project)
        before = snapshot(connection)
        connection.execute(text("UPDATE tasks SET priority=2 WHERE id=:id"), {"id": first})
    upgrade(database_url)
    with engine.begin() as connection:
        assert snapshot(connection) == before
        assert list(connection.execute(text("SELECT priority FROM tasks ORDER BY id")).scalars()) == [2, 0]
        _, _, last = insert_old_task(connection, "After contract", user_id=user, project_id=project)
        assert connection.scalar(text("SELECT priority FROM tasks WHERE id=:id"), {"id": last}) == 0


def test_invalid_existing_data_rolls_back_entire_migration(database_url, engine):
    upgrade(database_url, "002_expand")
    with engine.begin() as connection:
        user, project, bad = insert_old_task(connection)
        insert_old_task(connection, "Still NULL", user_id=user, project_id=project)
        connection.execute(text("UPDATE tasks SET priority=9 WHERE id=:id"), {"id": bad})
    with pytest.raises(IntegrityError):
        upgrade(database_url)
    with engine.connect() as connection:
        assert connection.scalar(text("SELECT version_num FROM alembic_version")) == "002_expand"
        assert list(connection.execute(text("SELECT priority FROM tasks ORDER BY id")).scalars()) == [9, None]
    columns = {column["name"]: column for column in inspect(engine).get_columns("tasks")}
    assert columns["priority"]["nullable"] is True
    assert columns["priority"]["default"] is None
    with engine.begin() as connection:
        connection.execute(text("UPDATE tasks SET priority=2 WHERE priority=9"))
    upgrade(database_url)
    command.check(configuration(database_url))


def test_data_losing_downgrade_is_refused(database_url, engine):
    upgrade(database_url)
    with engine.begin() as connection:
        insert_old_task(connection)
        before = snapshot(connection)
    with pytest.raises(RuntimeError, match="Refusing"):
        command.downgrade(configuration(database_url), "001_base")
    with engine.connect() as connection:
        assert snapshot(connection) == before
        assert connection.scalar(text("SELECT version_num FROM alembic_version")) == "003_contract"
    command.check(configuration(database_url))


def test_empty_downgrade_and_upgrade_roundtrip(database_url, engine):
    upgrade(database_url)
    command.downgrade(configuration(database_url), "base")
    assert inspect(engine).get_table_names() == ["alembic_version"]
    upgrade(database_url)
    command.check(configuration(database_url))


def test_autogenerate_detects_column_drift_not_a_data_audit(database_url, engine):
    upgrade(database_url)
    with engine.begin() as connection:
        connection.execute(text("ALTER TABLE tasks ADD COLUMN accidental text"))
    with pytest.raises(AutogenerateDiffsDetected):
        command.check(configuration(database_url))


def test_head_rejects_invalid_priority(database_url, engine):
    upgrade(database_url)
    with engine.begin() as connection:
        _, _, task = insert_old_task(connection)
    for value in (None, -1, 3):
        with pytest.raises(IntegrityError):
            with engine.begin() as connection:
                connection.execute(text("UPDATE tasks SET priority=:v WHERE id=:id"), {"v": value, "id": task})
    with engine.connect() as connection:
        assert connection.scalar(text("SELECT priority FROM tasks")) == 0

def test_autogenerate_rename_candidate_requires_human_review(database_url, engine, tmp_path):
    import shutil
    from pathlib import Path
    upgrade(database_url)
    with engine.begin() as connection:
        insert_old_task(connection)
        connection.execute(text("ALTER TABLE tasks RENAME COLUMN description TO note"))
    # Generate into a scratch script directory, never edit the shipped history.
    scripts = tmp_path / "migrations"
    shutil.copytree(Path(__file__).resolve().parents[1] / "migrations", scripts,
                    ignore=shutil.ignore_patterns("__pycache__"))
    config = configuration(database_url)
    config.set_main_option("script_location", str(scripts))
    candidate = command.revision(config, message="review rename candidate", autogenerate=True)
    source = Path(candidate.path).read_text()
    assert "op.add_column" in source and "op.drop_column" in source
    assert "description" in source and "note" in source
    with engine.connect() as connection:
        assert connection.scalar(text("SELECT note FROM tasks")) == "keep this note"
        assert connection.scalar(text("SELECT version_num FROM alembic_version")) == "003_contract"
